In [9]:
#importing data and selecting the index column

import pandas as pd
df= pd.read_csv('diamonds.csv',index_col=0)
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [11]:
##creating a dictionary for the non integer columns

cut_class_dict = {"Fair": 1, "Good": 2, "Very Good": 3, "Premium": 4, "Ideal": 5}
clarity_dict = {"I3": 1, "I2": 2, "I1": 3, "SI2": 4, "SI1": 5, "VS2": 6, "VS1": 7, "VVS2": 8, "VVS1": 9, "IF": 10, "FL": 11}
color_dict = {"J": 1,"I": 2,"H": 3,"G": 4,"F": 5,"E": 6,"D": 7}

In [13]:
#mapping the values to the dataset 

df['cut'] = df['cut'].map(cut_class_dict)
df['clarity'] = df['clarity'].map(clarity_dict)
df['color'] = df['color'].map(color_dict)
df.head()

   carat  cut  color  clarity  depth  table  price     x     y     z
1   0.23    5      6        4   61.5   55.0    326  3.95  3.98  2.43
2   0.21    4      6        5   59.8   61.0    326  3.89  3.84  2.31
3   0.23    2      6        7   56.9   65.0    327  4.05  4.07  2.31
4   0.29    4      2        6   62.4   58.0    334  4.20  4.23  2.63
5   0.31    2      1        4   63.3   58.0    335  4.34  4.35  2.75

In [21]:

import sklearn 
from sklearn import svm, preprocessing

In [22]:
df = sklearn.utils.shuffle(df)

X = df.drop("price", axis=1).values
X=preprocessing.scale(X)
y = df["price"].values

In [27]:
##defining test size 
test_size = 200

X_train = X[:-test_size]
y_train = y[:-test_size]

X_test = X[-test_size:]
y_test = y[-test_size:]

In [34]:
##printing the prediction score and the results 

clf = svm.SVR()

clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))


for X,y in list(zip(X_test, y_test))[:10]:
    print(f"model predicts {clf.predict([X])[0]}, real value: {y}")

0.5826131292289585
model predicts 852.5587260320558, real value: 646
model predicts 722.137914666057, real value: 596
model predicts 5067.32795856786, real value: 5612
model predicts 3138.1245224366344, real value: 2792
model predicts 4568.709075157294, real value: 4541
model predicts 1443.519557107875, real value: 1338
model predicts 1984.7099574738459, real value: 1608
model predicts 1836.5699869776058, real value: 1946
model predicts 644.4907351883508, real value: 465
model predicts 3602.9857711071904, real value: 3183